// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

using WS1IntelligenceIOS;

namespace WS1IntelligenceTestApp.iOS
{
	public partial class NetworkViewController : UIViewController
	{
		partial void network_error_manual_touchUpInside(Foundation.NSObject sender)
        {
			WS1Intelligence.LogNetworkRequest("GET", "https://www.google.ca", 1.22, 342, 77, 202, (IntPtr)null);
		}

		partial void network_event_manual_touchUpInside(Foundation.NSObject sender)
		{
			WS1Intelligence.LogNetworkRequest("GET", "https://www.google.ca", 1.22, 342, 77, 202, (IntPtr)null);
		}

		public NetworkViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
