// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

using WS1IntelligenceIOS;

namespace WS1IntelligenceTestApp.iOS
{
	public partial class OtherViewController : UIViewController
	{

		partial void breadcrumb_xamarin_touchUpInside(Foundation.NSObject sender)
		{
			WS1Intelligence.LeaveBreadcrumb("Xamarin breadcrumb");
		}

		partial void breadcrumb_async_touchUpInside(Foundation.NSObject sender)
		{
			WS1Intelligence.SetAsyncBreadcrumbMode(true);
		}

		partial void didCrashOnLastLoad_touchUpInside(Foundation.NSObject sender)
		{
			bool didCrashOnLastLoad = WS1Intelligence.DidCrashOnLastLoad();

			var alertController = UIAlertController.Create("Previous Session Crash Detected", didCrashOnLastLoad ? "true" : "false", UIAlertControllerStyle.Alert);

			alertController.AddAction(UIAlertAction.Create("OK", UIAlertActionStyle.Default, null));

			PresentViewController(alertController, true, null);
		}

		partial void optout_get_touchUpInside(Foundation.NSObject sender)
		{
			bool status = WS1Intelligence.GetOptOutStatus();

			var alertController = UIAlertController.Create("Opt-out Status", status ? "true" : "false", UIAlertControllerStyle.Alert);

			alertController.AddAction(UIAlertAction.Create("OK", UIAlertActionStyle.Default, null));

			PresentViewController(alertController, true, null);
		}

		partial void optout_toggle_touchUpInside(Foundation.NSObject sender)
		{
			bool currentStatus = WS1Intelligence.GetOptOutStatus();

			WS1Intelligence.SetOptOutStatus(!currentStatus);

			var alertController = UIAlertController.Create("Opt-out Status:", !currentStatus  ? "true" : "false", UIAlertControllerStyle.Alert);

			alertController.AddAction(UIAlertAction.Create("OK", UIAlertActionStyle.Default, null));

			PresentViewController(alertController, true, null);
		}

		partial void set_location_sf_touchUpInside(Foundation.NSObject sender)
		{
			WS1Intelligence.UpdateLocation(37.7749, -122.431297);
		}

		partial void set_location_toronto_touchUpInside(Foundation.NSObject sender)
		{
			WS1Intelligence.UpdateLocation(43.6532, -79.347015);
		}

		partial void set_username_xamarin_touchUpInside(Foundation.NSObject sender)
		{
			WS1Intelligence.SetUsername("xamarin");
		}

		partial void uuid_get_touchUpInside(Foundation.NSObject sender)
		{
			string uuid = WS1Intelligence.GetUserUUID();

			var alertController = UIAlertController.Create("User UUID", uuid, UIAlertControllerStyle.Alert);

			alertController.AddAction(UIAlertAction.Create("OK", UIAlertActionStyle.Default, null));

			PresentViewController(alertController, true, null);
		}

		public OtherViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
